import torch
x=torch.empty(1,2)
print(x)
y=torch.rand(2,3)
print("y",y)
z=torch.ones(2,4)
print("z", z)
a=torch.ones(2,4,dtype=torch.int)
print("a",a,a.dtype,a.size(),a.shape)
b=torch.tensor([2.5, 0.1])
print(b)
x=torch.rand(2, 4)
y=torch.rand(2, 4)
print("x", x)
print("y", y)
z=x+y
print("z", z)
z=torch.add(x, y)
print("z", z)
y.add_(x)
print("y", y)
z=torch.sub(x, y)
print('z',z)